INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Hamburguesa Clasica', 'Jugosa hamburguesa de carne de res con queso, lechuga y tomate', 7.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Ensalada Cesar', 'Fresca ensalada con pollo a la parrilla, crutones y aderezo Cesar', 9.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Sandwich de Pollo', 'Sandwich de pollo a la parrilla con tocino y queso cheddar', 8.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Sopa de Tomate', 'Sopa de tomate casera con trocitos de tomate fresco', 5.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Fajitas de Pollo', 'Fajitas de pollo a la parrilla con pimientos y cebolla', 12.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Pasta Alfredo', 'Pasta con salsa Alfredo y pollo a la parrilla', 11.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Ensalada de Frutas', 'Ensalada de frutas frescas con yogurt griego y granola', 6.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Tacos de Carne Asada', 'Tacos de carne asada con cebolla y cilantro', 10.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Pizza de Pepperoni', 'Pizza de pepperoni con queso mozzarella', 14.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Salmon a la Parrilla', 'Salmon a la parrilla con vegetales asados', 16.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Ensalada de Espinacas', 'Ensalada de espinacas con tocino, huevo y vinagreta de mostaza', 8.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Tarta de Manzana', 'Tarta de manzana casera con helado de vainilla', 6.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Alitas de Pollo', 'Alitas de pollo a la barbacoa con aderezo ranch', 9.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Wrap Vegano', 'Wrap vegano con hummus, aguacate y vegetales frescos', 7.99);
INSERT INTO platillos (nombre, descripcion, precio) VALUES ('Sandwich de Carne', 'Sandwich de carne asada con queso provolone y cebolla caramelizada', 11.99);